/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.evarino.actionbarsearch;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.app.Activity;


@Kroll.module(name="Actionbarsearch", id="com.evarino.actionbarsearch")
public class ActionbarsearchModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "ActionbarsearchModule";
	private static final boolean DBG = TiConfig.LOGD;

	public ActionbarsearchModule()
	{
		super();
	}

}

